import Clean.Backend.LLZK.Corpus

/-!
# Public example showcase

The data-to-document boundary for `doc/llzk/EXAMPLES.md`. Corpus names, fields,
vector counts, and source-agreement status come from `Corpus.corpus`; the short
purpose labels below are the only editorial metadata. An unknown corpus entry,
a failed module, an empty vector set, or a failed/half-present G9 result makes
generation fail rather than silently publishing an incomplete table.
-/

namespace LLZK.Showcase

/-- Why a corpus entry is useful to a public reader. Exhaustive over the current
corpus on purpose: adding an artifact requires choosing how it is presented. -/
def purpose : String → Option String
  | "Multiply" => some "Minimal proved source-to-LLZK vertical slice"
  | "Decompose" => some "Accepted `felt.umod` and `felt.uintdiv` witness shapes"
  | "LowByte" => some "Bounded `felt.bit_and` witness lowering"
  | "Bits8" => some "First-class `bitsOf` decomposition with felt shifts"
  | "Addition8FullCarry" => some "Headline proved byte addition with a certified lookup"
  | "Passthrough" => some "Direct public output with no witness cells"
  | "ConstOut" => some "Constant public output with no witness cells"
  | "CopyCell" => some "Copy-canonicalisation regression and proof boundary"
  | "Square_babybear" => some "LLZK field-registry conformance probe"
  | "Square_mersenne31" => some "LLZK field-registry conformance probe"
  | "Square_koalabear" => some "LLZK field-registry conformance probe"
  | "Square_goldilocks" => some "LLZK field-registry conformance probe"
  | "Square_bn254" => some "LLZK field-registry conformance probe"
  | "Square_grumpkin" => some "LLZK field-registry conformance probe"
  | _ => none

def isSourceBacked (entry : Corpus.Entry) : Bool :=
  entry.constraintsAgree = some true && entry.witnessAgree = some true

def totalVectors : Nat :=
  Corpus.corpus.foldl (fun total entry => total + entry.vectors.size) 0

def sourceBacked : Nat :=
  (Corpus.corpus.filter isSourceBacked).size

private def sourceLabel (entry : Corpus.Entry) : Except String String :=
  match entry.constraintsAgree, entry.witnessAgree with
  | some true, some true => .ok "yes — constraints and witnesses agree"
  | none, none => .ok "no — registry probe"
  | constraints, witnesses =>
      .error s!"{entry.name}: invalid G9 status: {repr constraints}, {repr witnesses}"

private def row (entry : Corpus.Entry) : Except String String := do
  match entry.module with
  | .error _ => throw s!"{entry.name}: module compilation failed"
  | .ok _ => pure ()
  if entry.vectors.isEmpty then
    throw s!"{entry.name}: public corpus entry has no input vectors"
  let some why := purpose entry.name
    | throw s!"{entry.name}: no public purpose label"
  let source ← sourceLabel entry
  return s!"| `{entry.name}` | `{entry.field.name}` | {source} | {entry.vectors.size} | {why} |"

private def findEntry (name : String) : Except String Corpus.Entry :=
  match Corpus.corpus.find? (·.name = name) with
  | some entry => .ok entry
  | none => .error s!"public headline entry {name} is absent from the corpus"

/-- Render the checked public example page. -/
def markdown : Except String String := do
  let headline ← findEntry "Addition8FullCarry"
  let rows ← Corpus.corpus.toList.mapM row
  let lines :=
    [ "# Verified example showcase"
    , ""
    , "<!-- Generated by Clean/Backend/LLZK/ShowcaseMain.lean."
    , "     Regenerate it; do not edit the corpus table by hand. -->"
    , ""
    , "This page is the compact public view of the examples that reach the complete"
    , "Clean → LLZK conformance path. Its table is generated from `LLZK.Corpus.corpus`,"
    , "and the full release gate regenerates and compares this file byte-for-byte."
    , ""
    , "## Headline example: `Addition8FullCarry`"
    , ""
    , "Clean's library gadget adds two bytes and a carry-in, returning the low byte"
    , "and carry-out. It carries Lean soundness and completeness proofs, uses the"
    , "certified 256-row byte lookup table, and is instantiated by"
    , "`Test/Soundness.add8_spec_of_compile`: under the gadget assumptions and the"
    , "named lookup hypothesis, satisfaction of the compiled typed module's"
    , "constraints implies the gadget's own `Spec`."
    , ""
    , s!"The corpus runs {headline.vectors.size} boundary-oriented vectors for this gadget. Three of them"
    , "are deliberately outside its assumptions: they do not test the gadget theorem,"
    , "but they do test that both LLZK witness backends reproduce Clean's witness"
    , "program even where `llzk-witgen` ignores `@constrain`."
    , ""
    , "- Source and proof:"
    , "  [`Clean/Gadgets/Addition8/Addition8FullCarry.lean`](../../Clean/Gadgets/Addition8/Addition8FullCarry.lean)."
    , "- Backend instantiation:"
    , "  [`Clean/Backend/LLZK/Test/Soundness.lean`](../../Clean/Backend/LLZK/Test/Soundness.lean)."
    , ""
    , "## Checked conformance corpus"
    , ""
    , s!"The current corpus contains {Corpus.corpus.size} emitted modules and {totalVectors} input vectors."
    , s!"{sourceBacked} modules come from a flattened Clean circuit and pass both halves of G9; the"
    , s!"remaining {Corpus.corpus.size - sourceBacked} are independent field-registry probes,"
    , "so source agreement is deliberately reported as not applicable rather than passing."
    , ""
    , "| Example | Field | Clean source agreement | Vectors | Purpose |"
    , "|---|---|---:|---:|---|" ]
    ++ rows ++
    [ ""
    , "Every row is parsed, verified, round-tripped, and admitted to LLZK's analysis"
    , "pipeline. Every vector is executed by both `llzk-witgen` backends and compared"
    , "against Clean's own witness interpreter. For source-backed rows, emission also"
    , "requires the typed `@constrain` and `@compute` readers to agree with the circuit."
    , ""
    , "## Assurance chain"
    , ""
    , "| Layer | Repository evidence |"
    , "|---|---|"
    , "| Gadget semantics | Clean soundness/completeness proofs; specific compiled implication for `Addition8FullCarry` |"
    , "| Lookup values | `byteTable_certified` proves the exported byte values |"
    , "| Typed translation | G9 independently reads source and module constraints and witnesses |"
    , "| Concrete constraint text | A5 parses the protected rendered surface back before returning text |"
    , "| Copy handling | A7 proves canonicalisation stepwise and across the witness-program list |"
    , "| LLZK tooling | G3–G7 and G10 exercise parsing, round trip, analysis, and both witness backends |"
    , ""
    , "## Reproduce"
    , ""
    , "From the repository root, after provisioning the pinned tools in"
    , "[`PINS.md`](PINS.md):"
    , ""
    , "```bash"
    , "export LLZK_SESSION=showcase"
    , "export LLZK_OPT=/path/to/pinned/llzk-opt"
    , "export LLZK_WITGEN=/path/to/pinned/llzk-witgen"
    , "bash scripts/llzk/worktree-lock.sh claim \"reproduce public showcase\""
    , "bash scripts/llzk/e2e.sh"
    , "```"
    , ""
    , "Regenerate this page explicitly with:"
    , ""
    , "```bash"
    , "lake env lean --run Clean/Backend/LLZK/ShowcaseMain.lean doc/llzk/EXAMPLES.md"
    , "```"
    , ""
    , "## Honest boundary"
    , ""
    , "This is a deep vertical slice, not broad Clean-library coverage. The corpus is"
    , "selected rather than exhaustive. Lean establishes properties of the typed module"
    , "and the renderer's protected surface, while the concrete semantics assigned by"
    , "LLZK remain the explicit D017 assumption. The caller-to-circuit lookup-table"
    , "identity gap also remains open. See [`GAPS.md`](GAPS.md) for the authoritative"
    , "claim boundary."
    ]
  return String.intercalate "\n" lines ++ "\n"

end LLZK.Showcase
